Modified the code for blog.devopsnotes.org subdomain only

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,3 +1,6 @@
+  variables:
+    TARGET_DIR: "blog-devopsnotes"
+    SERVER_IP: "113.30.191.17"
   deploy_production:
     stage: deploy
     tags:
@@ -8,20 +11,20 @@
       - ssh-add "$CI_CD_SSH_KEY"
       - mkdir -p ~/.ssh
       - chmod 700 ~/.ssh
-      - ssh-keyscan -H 113.30.191.17 >> ~/.ssh/known_hosts || echo "Keyscan failed"
+      - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts || echo "Keyscan failed"
     script:
       - echo "Vérification GitLab -> Longueur du token = ${#SENTRY_AUTH_TOKEN}"
       - |
-        ssh -A -o StrictHostKeyChecking=no kamal@113.30.191.17 "
+        ssh -A -o StrictHostKeyChecking=no kamal@SERVER_IP "
           export SENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}" &&
-          cd projet-demo-devops-v1 &&
+          cd $TARGET_DIR &&
           git pull origin main &&
           
           # --- GÉNÉRATION DU FICHIER .ENV BACKEND ---
           echo 'MONGODB_URI=${MONGODB_URI}' > ./backend/.env &&
           echo 'PORT=5000' >> ./backend/.env &&
-          echo 'FRONT_END_URL=https://www.devopsnotes.org' >> ./backend/.env &&
-          echo 'REACT_APP_API_URL=https://www.devopsnotes.org/api' >> ./backend/.env &&
+          echo 'FRONT_END_URL=https://blog.devopsnotes.org' >> ./backend/.env &&
+          echo 'REACT_APP_API_URL=https://blog.devopsnotes.org/api' >> ./backend/.env &&
           echo 'ADMIN_EMAIL=${ADMIN_EMAIL}' >> ./backend/.env &&
           echo 'ADMIN_PASSWORD=${ADMIN_PASSWORD}' >> ./backend/.env &&
           echo 'JWT_SECRET=${JWT_SECRET}' >> ./backend/.env &&
@@ -37,9 +40,9 @@
           echo 'R2_PUBLIC_URL=${R2_PUBLIC_URL}' >> ./backend/.env &&
 
           # --- GÉNÉRATION DU FICHIER .ENV FRONTEND ---
-          echo 'REACT_APP_API_URL=https://www.devopsnotes.org/api' > ./frontend/.env &&
+          echo 'REACT_APP_API_URL=https://blog.devopsnotes.org/api' > ./frontend/.env &&
           echo 'NODE_ENV=production' >> ./frontend/.env &&
-          echo 'REACT_APP_ROOT=https://www.devopsnotes.org' >> ./frontend/.env &&
+          echo 'REACT_APP_ROOT=https://blog.devopsnotes.org' >> ./frontend/.env &&
           echo 'REACT_APP_R2_PUBLIC_URL=${R2_PUBLIC_URL}' >> ./frontend/.env &&
 
           
