New tests for Sentry

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,48 +1,48 @@
-deploy_production:
-  stage: deploy
-  tags:
-    - deploy_production
-  before_script:
-    - eval $(ssh-agent -s)
-    - chmod 600 "$CI_CD_SSH_KEY"
-    - ssh-add "$CI_CD_SSH_KEY"
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - ssh-keyscan -H 113.30.191.17 >> ~/.ssh/known_hosts || echo "Keyscan failed"
-  script:
-    - |
-      ssh -A -o StrictHostKeyChecking=no kamal@113.30.191.17 "
-        export SENTRY_AUTH_TOKEN='${SENTRY_AUTH_TOKEN}' &&
-        cd projet-demo-devops-v1 &&
-        git pull origin main &&
-        
-        # --- GÉNÉRATION DU FICHIER .ENV BACKEND ---
-        echo 'MONGODB_URI=${MONGODB_URI}' > ./backend/.env &&
-        echo 'PORT=5000' >> ./backend/.env &&
-        echo 'FRONT_END_URL=https://www.devopsnotes.org' >> ./backend/.env &&
-        echo 'REACT_APP_API_URL=https://www.devopsnotes.org/api' >> ./backend/.env &&
-        echo 'ADMIN_EMAIL=${ADMIN_EMAIL}' >> ./backend/.env &&
-        echo 'ADMIN_PASSWORD=${ADMIN_PASSWORD}' >> ./backend/.env &&
-        echo 'JWT_SECRET=${JWT_SECRET}' >> ./backend/.env &&
-        echo 'JWT_EXPIRES=1h' >> ./backend/.env &&
-        echo 'RESEND_API_KEY=${RESEND_API_KEY}' >> ./backend/.env &&
-        echo "SENTRY_DSN=${SENTRY_DSN}" >> ./backend/.env
-        
-        # Configuration Cloudflare R2
-        echo 'R2_ACCOUNT_ID=${R2_ACCOUNT_ID}' >> ./backend/.env &&
-        echo 'R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}' >> ./backend/.env &&
-        echo 'R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}' >> ./backend/.env &&
-        echo 'R2_BUCKET_NAME=${R2_BUCKET_NAME}' >> ./backend/.env &&
-        echo 'R2_PUBLIC_URL=${R2_PUBLIC_URL}' >> ./backend/.env &&
+  deploy_production:
+    stage: deploy
+    tags:
+      - deploy_production
+    before_script:
+      - eval $(ssh-agent -s)
+      - chmod 600 "$CI_CD_SSH_KEY"
+      - ssh-add "$CI_CD_SSH_KEY"
+      - mkdir -p ~/.ssh
+      - chmod 700 ~/.ssh
+      - ssh-keyscan -H 113.30.191.17 >> ~/.ssh/known_hosts || echo "Keyscan failed"
+    script:
+      - |
+        ssh -A -o StrictHostKeyChecking=no kamal@113.30.191.17 "
+          export SENTRY_AUTH_TOKEN='${SENTRY_AUTH_TOKEN}' &&
+          cd projet-demo-devops-v1 &&
+          git pull origin main &&
+          
+          # --- GÉNÉRATION DU FICHIER .ENV BACKEND ---
+          echo 'MONGODB_URI=${MONGODB_URI}' > ./backend/.env &&
+          echo 'PORT=5000' >> ./backend/.env &&
+          echo 'FRONT_END_URL=https://www.devopsnotes.org' >> ./backend/.env &&
+          echo 'REACT_APP_API_URL=https://www.devopsnotes.org/api' >> ./backend/.env &&
+          echo 'ADMIN_EMAIL=${ADMIN_EMAIL}' >> ./backend/.env &&
+          echo 'ADMIN_PASSWORD=${ADMIN_PASSWORD}' >> ./backend/.env &&
+          echo 'JWT_SECRET=${JWT_SECRET}' >> ./backend/.env &&
+          echo 'JWT_EXPIRES=1h' >> ./backend/.env &&
+          echo 'RESEND_API_KEY=${RESEND_API_KEY}' >> ./backend/.env &&
+          echo 'SENTRY_DSN=${SENTRY_DSN}' >> ./backend/.env &&
+          
+          # Configuration Cloudflare R2
+          echo 'R2_ACCOUNT_ID=${R2_ACCOUNT_ID}' >> ./backend/.env &&
+          echo 'R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}' >> ./backend/.env &&
+          echo 'R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}' >> ./backend/.env &&
+          echo 'R2_BUCKET_NAME=${R2_BUCKET_NAME}' >> ./backend/.env &&
+          echo 'R2_PUBLIC_URL=${R2_PUBLIC_URL}' >> ./backend/.env &&
 
-        # --- GÉNÉRATION DU FICHIER .ENV FRONTEND ---
-        echo 'REACT_APP_API_URL=https://www.devopsnotes.org/api' > ./frontend/.env &&
-        echo 'NODE_ENV=production' >> ./frontend/.env &&
-        echo 'REACT_APP_ROOT=https://www.devopsnotes.org' >> ./frontend/.env &&
-        echo 'REACT_APP_R2_PUBLIC_URL=${R2_PUBLIC_URL}' >> ./frontend/.env &&
+          # --- GÉNÉRATION DU FICHIER .ENV FRONTEND ---
+          echo 'REACT_APP_API_URL=https://www.devopsnotes.org/api' > ./frontend/.env &&
+          echo 'NODE_ENV=production' >> ./frontend/.env &&
+          echo 'REACT_APP_ROOT=https://www.devopsnotes.org' >> ./frontend/.env &&
+          echo 'REACT_APP_R2_PUBLIC_URL=${R2_PUBLIC_URL}' >> ./frontend/.env &&
 
-        
-        # --- RELANCE DE DOCKER ---
-        docker compose down &&
-        docker compose up -d --build --force-recreate --remove-orphans
-      "
+          
+          # --- RELANCE DE DOCKER ---
+          docker compose down &&
+          docker compose up -d --build --force-recreate --remove-orphans
+        "
